<?php

use Illuminate\Database\Seeder;

class AdultosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('adultos')->truncate();
    DB::table('adultos')->insert(['Codigo' => '4005808257584','NombreProducto' => 'productounoa','NombreVariable' =>  'unoa', 'NombrePrecio' =>  'preciounoa','NombreTotalPrecio' =>'totalpreciounoa','DescripcionProducto' => 'NIVEA Deo Rollon 50 gr.','Precio'=> '110','NombrePirce'=>'pirceunoa','NombreDiv'=>'totalunoa','image'=>'imga (1).jpg']);
DB::table('adultos')->insert(['Codigo' => '7790626204090','NombreProducto' => 'productodosa','NombreVariable' =>  'dosa', 'NombrePrecio' =>  'preciodosa','NombreTotalPrecio' =>'totalpreciodosa','DescripcionProducto' => 'FULTON Colonia Rosas 250 ml.','Precio'=> '350 ','NombrePirce'=>'pircedosa','NombreDiv'=>'totaldosa','image'=>'imga (2).jpg']);
DB::table('adultos')->insert(['Codigo' => '7790626011629','NombreProducto' => 'productotresa','NombreVariable' =>  'tresa', 'NombrePrecio' =>  'preciotresa','NombreTotalPrecio' =>'totalpreciotresa','DescripcionProducto' => 'FULTON jabón Jazmín 2 x100 gr.','Precio'=> '280','NombrePirce'=>'pircetresa','NombreDiv'=>'totaltresa','image'=>'imga (3).jpg']);
DB::table('adultos')->insert(['Codigo' => '7791520003093','NombreProducto' => 'productocuatroa','NombreVariable' =>  'cuatroa', 'NombrePrecio' =>  'preciocuatroa','NombreTotalPrecio' =>'totalpreciocuatroa','DescripcionProducto' => 'FARMACO Jabón de Glicerina Neutro 120 gr.','Precio'=> '99 ','NombrePirce'=>'pircecuatroa','NombreDiv'=>'totalcuatroa','image'=>'imga (4).jpg']);
DB::table('adultos')->insert(['Codigo' => '7791520002072','NombreProducto' => 'productocincoa','NombreVariable' =>  'cincoa', 'NombrePrecio' =>  'preciocincoa','NombreTotalPrecio' =>'totalpreciocincoa','DescripcionProducto' => 'FARMACO jabón de Coco (Cabello y piel grasa) 100 gr.','Precio'=> '99','NombrePirce'=>'pircecincoa','NombreDiv'=>'totalcincoa','image'=>'imga (5).jpg']);
DB::table('adultos')->insert(['Codigo' => '4005808321216','NombreProducto' => 'productoseisa','NombreVariable' =>  'seisa', 'NombrePrecio' =>  'precioseisa','NombreTotalPrecio' =>'totalprecioseisa','DescripcionProducto' => 'NIVEA Body Piel Seca 250 ml','Precio'=> '250','NombrePirce'=>'pirceseisa','NombreDiv'=>'totalseisa','image'=>'imga (6).jpg']);
DB::table('adultos')->insert(['Codigo' => '7793742007330','NombreProducto' => 'productosietea','NombreVariable' =>  'sietea', 'NombrePrecio' =>  'preciosietea','NombreTotalPrecio' =>'totalpreciosietea','DescripcionProducto' => 'DERMAGLOS corporal Hidratación Inmediata 175 ml','Precio'=> '575 ','NombrePirce'=>'pircesietea','NombreDiv'=>'totalsietea','image'=>'imga (7).jpg']);
DB::table('adultos')->insert(['Codigo' => '7793742007910','NombreProducto' => 'productoochoa','NombreVariable' =>  'ochoa', 'NombrePrecio' =>  'precioochoa','NombreTotalPrecio' =>'totalprecioochoa','DescripcionProducto' => 'DERMAGLOS Crema Manos y Uñas 50 gr.','Precio'=> '310 ','NombrePirce'=>'pirceochoa','NombreDiv'=>'totalochoa','image'=>'imga (8).jpg']);
DB::table('adultos')->insert(['Codigo' => '7793742007675','NombreProducto' => 'productonuevea','NombreVariable' =>  'nuevea', 'NombrePrecio' =>  'precionuevea','NombreTotalPrecio' =>'totalprecionuevea','DescripcionProducto' => 'DERMAGLOS Corporal Regeneración Intensa 300 ml','Precio'=> '790 ','NombrePirce'=>'pircenuevea','NombreDiv'=>'totalnuevea','image'=>'imga (9).jpg']);
DB::table('adultos')->insert(['Codigo' => '7793742001482','NombreProducto' => 'productodieza','NombreVariable' =>  'dieza', 'NombrePrecio' =>  'preciodieza','NombreTotalPrecio' =>'totalpreciodieza','DescripcionProducto' => 'DERMAGLOS Emulsión 100 ml','Precio'=> '410','NombrePirce'=>'pircedieza','NombreDiv'=>'totaldieza','image'=>'imga (10).jpg']);
DB::table('adultos')->insert(['Codigo' => '7790375004378','NombreProducto' => 'productooncea','NombreVariable' =>  'oncea', 'NombrePrecio' =>  'preciooncea','NombreTotalPrecio' =>'totalpreciooncea','DescripcionProducto' => 'BAGOVIT Emulsión, Cuidados Cotidianos, Efecto Seda!. 200 ml','Precio'=> '480 ','NombrePirce'=>'pirceoncea','NombreDiv'=>'totaloncea','image'=>'imga (11).jpg']);
DB::table('adultos')->insert(['Codigo' => '7790375267285','NombreProducto' => 'productodocea','NombreVariable' =>  'docea', 'NombrePrecio' =>  'preciodocea','NombreTotalPrecio' =>'totalpreciodocea','DescripcionProducto' => ' BAGOVIT Emulsión 350 ml','Precio'=> '735','NombrePirce'=>'pircedocea','NombreDiv'=>'totaldocea','image'=>'imga (12).jpg']);
DB::table('adultos')->insert(['Codigo' => '7793680001735','NombreProducto' => 'productotrecea','NombreVariable' =>  'trecea', 'NombrePrecio' =>  'preciotrecea','NombreTotalPrecio' =>'totalpreciotrecea','DescripcionProducto' => 'ROBY Spray Fijador 180 ml','Precio'=> '210 ','NombrePirce'=>'pircetrecea','NombreDiv'=>'totaltrecea','image'=>'imga (13).jpg']);
DB::table('adultos')->insert(['Codigo' => '7702018053476','NombreProducto' => 'productocatorcea','NombreVariable' =>  'catorcea', 'NombrePrecio' =>  'preciocatorcea','NombreTotalPrecio' =>'totalpreciocatorcea','DescripcionProducto' => 'GILLETTE Foamy 175 gr.','Precio'=> '170','NombrePirce'=>'pircecatorcea','NombreDiv'=>'totalcatorcea','image'=>'imga (14).jpg']);
DB::table('adultos')->insert(['Codigo' => '474000179240','NombreProducto' => 'productoquincea','NombreVariable' =>  'quincea', 'NombrePrecio' =>  'precioquincea','NombreTotalPrecio' =>'totalprecioquincea','DescripcionProducto' => 'GILLETTE Mach3 Cartuchos x 2','Precio'=> '320','NombrePirce'=>'pircequincea','NombreDiv'=>'totalquincea','image'=>'imga (15).jpg']);
DB::table('adultos')->insert(['Codigo' => '7791293035932','NombreProducto' => 'productodieciseisa','NombreVariable' =>  'dieciseisa', 'NombrePrecio' =>  'preciodieciseisa','NombreTotalPrecio' =>'totalpreciodieciseisa','DescripcionProducto' => 'PATRICHS Noir Aerosol 97 gr.','Precio'=> '110 ','NombrePirce'=>'pircedieciseisa','NombreDiv'=>'totaldieciseisa','image'=>'imga (16).jpg']);
DB::table('adultos')->insert(['Codigo' => '77912930020419','NombreProducto' => 'productodiecisietea','NombreVariable' =>  'diecisietea', 'NombrePrecio' =>  'preciodiecisietea','NombreTotalPrecio' =>'totalpreciodiecisietea','DescripcionProducto' => 'PATRICHS Colonia Terra EDT 50 ml','Precio'=> '250','NombrePirce'=>'pircediecisietea','NombreDiv'=>'totaldiecisietea','image'=>'imga (17).jpg']);
DB::table('adultos')->insert(['Codigo' => '7791600284039','NombreProducto' => 'productodieciochoa','NombreVariable' =>  'dieciochoa', 'NombrePrecio' =>  'preciodieciochoa','NombreTotalPrecio' =>'totalpreciodieciochoa','DescripcionProducto' => 'ACQUA DI COLBERT Desodorante Sin Alcohol Ultra seco 177 gr.','Precio'=> '199','NombrePirce'=>'pircedieciochoa','NombreDiv'=>'totaldieciochoa','image'=>'imga (18).jpg']);
DB::table('adultos')->insert(['Codigo' => '7791600028190','NombreProducto' => 'productodiecinuevea','NombreVariable' =>  'diecinuevea', 'NombrePrecio' =>  'preciodiecinuevea','NombreTotalPrecio' =>'totalpreciodiecinuevea','DescripcionProducto' => 'ACQUA DI COLBERT EDT C/Vap 60 ml','Precio'=> '439 ','NombrePirce'=>'pircediecinuevea','NombreDiv'=>'totaldiecinuevea','image'=>'imga (19).jpg']);
DB::table('adultos')->insert(['Codigo' => '7500435019484','NombreProducto' => 'productoveintea','NombreVariable' =>  'veintea', 'NombrePrecio' =>  'precioveintea','NombreTotalPrecio' =>'totalprecioveintea','DescripcionProducto' => 'HEAD  SHOULDERS 3 en 180 ml','Precio'=> '190','NombrePirce'=>'pirceveintea','NombreDiv'=>'totalveintea','image'=>'imga (20).jpg']);
DB::table('adultos')->insert(['Codigo' => '7794626002007','NombreProducto' => 'productoveintiunoa','NombreVariable' =>  'veintiunoa', 'NombrePrecio' =>  'precioveintiunoa','NombreTotalPrecio' =>'totalprecioveintiunoa','DescripcionProducto' => 'PLENITUD Apósitos Incontinencia LEVE 10 Unid.','Precio'=> '140','NombrePirce'=>'pirceveintiunoa','NombreDiv'=>'totalveintiunoa','image'=>'imga (21).jpg']);
DB::table('adultos')->insert(['Codigo' => '7794626006364','NombreProducto' => 'productoveintidosa','NombreVariable' =>  'veintidosa', 'NombrePrecio' =>  'precioveintidosa','NombreTotalPrecio' =>'totalprecioveintidosa','DescripcionProducto' => 'PLENITUD FEMME Toallas Largas C/Alas x8 Unid.','Precio'=> '330 ','NombrePirce'=>'pirceveintidosa','NombreDiv'=>'totalveintidosa','image'=>'imga (22).jpg']);
DB::table('adultos')->insert(['Codigo' => '7794626007385','NombreProducto' => 'productoveintitresa','NombreVariable' =>  'veintitresa', 'NombrePrecio' =>  'precioveintitresa','NombreTotalPrecio' =>'totalprecioveintitresa','DescripcionProducto' => ' PLENITUD FEMME Toallas Nocturnas x 8 Unid.','Precio'=> '670 ','NombrePirce'=>'pirceveintitresa','NombreDiv'=>'totalveintitresa','image'=>'imga (23).jpg']);
DB::table('adultos')->insert(['Codigo' => '7794626006708','NombreProducto' => 'productoveinticuatroa','NombreVariable' =>  'veinticuatroa', 'NombrePrecio' =>  'precioveinticuatroa','NombreTotalPrecio' =>'totalprecioveinticuatroa','DescripcionProducto' => 'PLENITUD PROTECT Pañal Descartable x 8 Unid.','Precio'=> '920','NombrePirce'=>'pirceveinticuatroa','NombreDiv'=>'totalveinticuatroa','image'=>'imga (24).jpg']);
DB::table('adultos')->insert(['Codigo' => '7896007550050','NombreProducto' => 'productoveinticincoa','NombreVariable' =>  'veinticincoa', 'NombrePrecio' =>  'precioveinticincoa','NombreTotalPrecio' =>'totalprecioveinticincoa','DescripcionProducto' => 'PLENITUD FEMME Ropa Interior Desechable x 8 Unid.','Precio'=> '890','NombrePirce'=>'pirceveinticincoa','NombreDiv'=>'totalveinticincoa','image'=>'imga (25).jpg']);
DB::table('adultos')->insert(['Codigo' => '7896007547203','NombreProducto' => 'productoveintiseisa','NombreVariable' =>  'veintiseisa', 'NombrePrecio' =>  'precioveintiseisa','NombreTotalPrecio' =>'totalprecioveintiseisa','DescripcionProducto' => ' PLENITUD PROTEC PLUS Interior Desechable x 16 Unid.','Precio'=> '1750 ','NombrePirce'=>'pirceveintiseisa','NombreDiv'=>'totalveintiseisa','image'=>'imga (26).jpg']);
DB::table('adultos')->insert(['Codigo' => '7791229152917','NombreProducto' => 'productoveintisietea','NombreVariable' =>  'veintisietea', 'NombrePrecio' =>  'precioveintisietea','NombreTotalPrecio' =>'totalprecioveintisietea','DescripcionProducto' => 'COMODIN ULTRA Pañales Anatómicos elastizados x 8 Unid..','Precio'=> '290','NombrePirce'=>'pirceveintisietea','NombreDiv'=>'totalveintisietea','image'=>'imga (27).jpg']);
DB::table('adultos')->insert(['Codigo' => '7791229153136','NombreProducto' => 'productoveintiochoa','NombreVariable' =>  'veintiochoa', 'NombrePrecio' =>  'precioveintiochoa','NombreTotalPrecio' =>'totalprecioveintiochoa','DescripcionProducto' => 'COMODIN Practibaño Jabonoso x 10Unid.','Precio'=> '240','NombrePirce'=>'pirceveintiochoa','NombreDiv'=>'totalveintiochoa','image'=>'imga (28).jpg']);
DB::table('adultos')->insert(['Codigo' => '7794640171765','NombreProducto' => 'productoveintinuevea','NombreVariable' =>  'veintinuevea', 'NombrePrecio' =>  'precioveintinuevea','NombreTotalPrecio' =>'totalprecioveintinuevea','DescripcionProducto' =>  'COREGA ULTRA Crema 70 gr.','Precio'=> '390','NombrePirce'=>'pirceveintinuevea','NombreDiv'=>'totalveintinuevea','image'=>'imga (29).jpg']);
DB::table('adultos')->insert(['Codigo' => '7794640171420','NombreProducto' => 'productotreintaa','NombreVariable' =>  'treintaa', 'NombrePrecio' =>  'preciotreintaa','NombreTotalPrecio' =>'totalpreciotreintaa','DescripcionProducto' => 'COREGA TABS Combine x 30 Tab.','Precio'=> '250','NombrePirce'=>'pircetreintaa','NombreDiv'=>'totaltreintaa','image'=>'imga (30).jpg']);

    }
}
