<?php

use Illuminate\Database\Seeder;

class BucalesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {   DB::table('bucales')->truncate();
       DB::table('bucales')->insert(['Codigo' =>'12344','NombreProducto' => 'productounoo','NombreVariable' =>  'unoo','NombrePrecio' =>'preciounoo','NombreTotalPrecio' =>'totalpreciounoo','DescripcionProducto' => 'ORAL-B CR DENT 3D WHITE BRILLANT X 70 X 6','Precio'=> '310 ','NombrePirce'=>'pirceunoo','NombreDiv'=>'totalunoo','image'=>'imgo (1).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12345','NombreProducto' => 'productodoso','NombreVariable' =>  'doso','NombrePrecio' =>'preciodoso','NombreTotalPrecio' =>'totalpreciodoso','DescripcionProducto' => 'ORAL-B CR DENT 3D WHITENING ESMAL DEF X 103','Precio'=> '330 ','NombrePirce'=>'pircedoso','NombreDiv'=>'totaldoso','image'=>'imgo (2).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12344','NombreProducto' => 'productotreso','NombreVariable' =>  'treso','NombrePrecio' =>'preciotreso','NombreTotalPrecio' =>'totalpreciotreso','DescripcionProducto' => 'ORAL-B CR DENT PRO GENGIVA SENSIT X 90','Precio'=> '310','NombrePirce'=>'pircetreso','NombreDiv'=>'totaltreso','image'=>'imgo (3).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12345','NombreProducto' => 'productocuatroo','NombreVariable' =>  'cuatroo','NombrePrecio' =>'preciocuatroo','NombreTotalPrecio' =>'totalpreciocuatroo','DescripcionProducto' => 'ORAL-B HILO DENTAL SUPER FLOSS X 50','Precio'=> '310','NombrePirce'=>'pircecuatroo','NombreDiv'=>'totalcuatroo','image'=>'imgo (4).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12344','NombreProducto' => 'productocincoo','NombreVariable' =>  'cincoo','NombrePrecio' =>'preciocincoo','NombreTotalPrecio' =>'totalpreciocincoo','DescripcionProducto' => 'ORAL-B PACK CR 3D WHITE 2X75ML','Precio'=> '255','NombrePirce'=>'pircecincoo','NombreDiv'=>'totalcincoo','image'=>'imgo (5).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12345','NombreProducto' => 'productoseiso','NombreVariable' =>  'seiso','NombrePrecio' =>'precioseiso','NombreTotalPrecio' =>'totalprecioseiso','DescripcionProducto' => 'ORAL-B RTO INTERDENTAL CILINDRICO','Precio'=> '330','NombrePirce'=>'pirceseiso','NombreDiv'=>'totalseiso','image'=>'imgo (6).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12344','NombreProducto' => 'productosieteo','NombreVariable' =>  'sieteo','NombrePrecio' =>'preciosieteo','NombreTotalPrecio' =>'totalpreciosieteo','DescripcionProducto' => 'ORAL-B CEP CLASSIC 40 3X2','Precio'=> '210','NombrePirce'=>'pircesieteo','NombreDiv'=>'totalsieteo','image'=>'imgo (7).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12345','NombreProducto' => 'productoochoo','NombreVariable' =>  'ochoo','NombrePrecio' =>'precioochoo','NombreTotalPrecio' =>'totalprecioochoo','DescripcionProducto' => 'ORAL-B CEP INDIC PLUS 30SFT SUAVE','Precio'=> '230','NombrePirce'=>'pirceochoo','NombreDiv'=>'totalochoo','image'=>'imgo (8).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12344','NombreProducto' => 'productonueveo','NombreVariable' =>  'nueveo','NombrePrecio' =>'precionueveo','NombreTotalPrecio' =>'totalprecionueveo','DescripcionProducto' => ' ORAL-B 3D WHITE ADVANCE 40S 2X1','Precio'=> '290','NombrePirce'=>'pircenueveo','NombreDiv'=>'totalnueveo','image'=>'imgo (9).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12345','NombreProducto' => 'productodiezo','NombreVariable' =>  'diezo','NombrePrecio' =>'preciodiezo','NombreTotalPrecio' =>'totalpreciodiezo','DescripcionProducto' => 'ORAL-B CEP COLOR PACK FAMILIAR X 5U','Precio'=> '390 ','NombrePirce'=>'pircediezo','NombreDiv'=>'totaldiezo','image'=>'imgo (10).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12344','NombreProducto' => 'productoonceo','NombreVariable' =>  'onceo','NombrePrecio' =>'precioonceo','NombreTotalPrecio' =>'totalprecioonceo','DescripcionProducto' => ' COLGATE CEP 360º LUMINOUS 2X1','Precio'=> '350','NombrePirce'=>'pirceonceo','NombreDiv'=>'totalonceo','image'=>'imgo (11).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12345','NombreProducto' => 'productodoceo','NombreVariable' =>  'doceo','NombrePrecio' =>'preciodoceo','NombreTotalPrecio' =>'totalpreciodoceo','DescripcionProducto' => 'COLGATE CEP BAMBOO','Precio'=> '280 ','NombrePirce'=>'pircedoceo','NombreDiv'=>'totaldoceo','image'=>'imgo (12).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12344','NombreProducto' => 'productotreceo','NombreVariable' =>  'treceo','NombrePrecio' =>'preciotreceo','NombreTotalPrecio' =>'totalpreciotreceo','DescripcionProducto' => 'COLGATE CEP CLASIC MEDIANO','Precio'=> '70 ','NombrePirce'=>'pircetreceo','NombreDiv'=>'totaltreceo','image'=>'imgo (13).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12345','NombreProducto' => 'productocatorceo','NombreVariable' =>  'catorceo','NombrePrecio' =>'preciocatorceo','NombreTotalPrecio' =>'totalpreciocatorceo','DescripcionProducto' => 'COLGATE CEP SLIM SOFT 2X1','Precio'=> '390 ','NombrePirce'=>'pircecatorceo','NombreDiv'=>'totalcatorceo','image'=>'imgo (14).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12344','NombreProducto' => 'productoquinceo','NombreVariable' =>  'quinceo','NombrePrecio' =>'precioquinceo','NombreTotalPrecio' =>'totalprecioquinceo','DescripcionProducto' => 'COLGATE CEP MAX WHITE 2X1 MEDIANO','Precio'=> '250','NombrePirce'=>'pircequinceo','NombreDiv'=>'totalquinceo','image'=>'imgo (15).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12345','NombreProducto' => 'productodieciseiso','NombreVariable' =>  'dieciseiso','NombrePrecio' =>'preciodieciseiso','NombreTotalPrecio' =>'totalpreciodieciseiso','DescripcionProducto' => 'COLGATE CR EXT NATURAL DETOX X 90','Precio'=> '210','NombrePirce'=>'pircedieciseiso','NombreDiv'=>'totaldieciseiso','image'=>'imgo (16).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12344','NombreProducto' => 'productodiecisieteo','NombreVariable' =>  'diecisieteo','NombrePrecio' =>'preciodiecisieteo','NombreTotalPrecio' =>'totalpreciodiecisieteo','DescripcionProducto' => 'COLGATE CR HERBAL BLANQ BRILL X90','Precio'=> '110','NombrePirce'=>'pircediecisieteo','NombreDiv'=>'totaldiecisieteo','image'=>'imgo (17).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12345','NombreProducto' => 'productodieciochoo','NombreVariable' =>  'dieciochoo','NombrePrecio' =>'preciodieciochoo','NombreTotalPrecio' =>'totalpreciodieciochoo','DescripcionProducto' => 'COLGATE CR ORIG INTERDENTAL X 70','Precio'=> '90 ','NombrePirce'=>'pircedieciochoo','NombreDiv'=>'totaldieciochoo','image'=>'imgo (18).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12344','NombreProducto' => 'productodiecinueveo','NombreVariable' =>  'diecinueveo','NombrePrecio' =>'preciodiecinueveo','NombreTotalPrecio' =>'totalpreciodiecinueveo','DescripcionProducto' => 'COLGATE CR SENS PROALIVIO INMEDIAT ORIG X 90','Precio'=> '260 ','NombrePirce'=>'pircediecinueveo','NombreDiv'=>'totaldiecinueveo','image'=>'imgo (19).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12345','NombreProducto' => 'productoveinteo','NombreVariable' =>  'veinteo','NombrePrecio' =>'precioveinteo','NombreTotalPrecio' =>'totalprecioveinteo','DescripcionProducto' => 'COLGATE CR ULTRA WHITE X 90','Precio'=> '150','NombrePirce'=>'pirceveinteo','NombreDiv'=>'totalveinteo','image'=>'imgo (20).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12344','NombreProducto' => 'productoveintiunoo','NombreVariable' =>  'veintiunoo','NombrePrecio' =>'precioveintiunoo','NombreTotalPrecio' =>'totalprecioveintiunoo','DescripcionProducto' => 'COLGATE ENJ BUCAL TOTAL 12 ANTISARRO X 250','Precio'=> '310','NombrePirce'=>'pirceveintiunoo','NombreDiv'=>'totalveintiunoo','image'=>'imgo (21).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12345','NombreProducto' => 'productoveintidoso','NombreVariable' =>  'veintidoso','NombrePrecio' =>'precioveintidoso','NombreTotalPrecio' =>'totalprecioveintidoso','DescripcionProducto' => 'COLGATE ENJ BUCAL TOTAL BREATH HEALTH X 250','Precio'=> '310','NombrePirce'=>'pirceveintidoso','NombreDiv'=>'totalveintidoso','image'=>'imgo (22).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12344','NombreProducto' => 'productoveintitreso','NombreVariable' =>  'veintitreso','NombrePrecio' =>'precioveintitreso','NombreTotalPrecio' =>'totalprecioveintitreso','DescripcionProducto' => 'COLGATE ENJ BUCAL TOTAL BREATH HEALTH X 500','Precio'=> '440','NombrePirce'=>'pirceveintitreso','NombreDiv'=>'totalveintitreso','image'=>'imgo (23).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12345','NombreProducto' => 'productoveinticuatroo','NombreVariable' =>  'veinticuatroo','NombrePrecio' =>'precioveinticuatroo','NombreTotalPrecio' =>'totalprecioveinticuatroo','DescripcionProducto' => 'LISTERINE CONTROL ZERO SARRO X 500ML','Precio'=> '415 ','NombrePirce'=>'pirceveinticuatroo','NombreDiv'=>'totalveinticuatroo','image'=>'imgo (24).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12344','NombreProducto' => 'productoveinticincoo','NombreVariable' =>  'veinticincoo','NombrePrecio' =>'precioveinticincoo','NombreTotalPrecio' =>'totalprecioveinticincoo','DescripcionProducto' => 'LISTERINE FRESH BURSTX500','Precio'=> '350','NombrePirce'=>'pirceveinticincoo','NombreDiv'=>'totalveinticincoo','image'=>'imgo (25).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12345','NombreProducto' => 'productoveintiseiso','NombreVariable' =>  'veintiseiso','NombrePrecio' =>'precioveintiseiso','NombreTotalPrecio' =>'totalprecioveintiseiso','DescripcionProducto' => ' LISTERINE PROT ENCIAS X250','Precio'=> '310 ','NombrePirce'=>'pirceveintiseiso','NombreDiv'=>'totalveintiseiso','image'=>'imgo (26).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12344','NombreProducto' => 'productoveintisieteo','NombreVariable' =>  'veintisieteo','NombrePrecio' =>'precioveintisieteo','NombreTotalPrecio' =>'totalprecioveintisieteo','DescripcionProducto' => 'LISTERINE TOTAL CON FLUOR X 250ML','Precio'=> '310 ','NombrePirce'=>'pirceveintisieteo','NombreDiv'=>'totalveintisieteo','image'=>'imgo (27).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12345','NombreProducto' => 'productoveintiochoo','NombreVariable' =>  'veintiochoo','NombrePrecio' =>'precioveintiochoo','NombreTotalPrecio' =>'totalprecioveintiochoo','DescripcionProducto' => 'GUM CEP CLASSIC 311 SUAVE','Precio'=> '240','NombrePirce'=>'pirceveintiochoo','NombreDiv'=>'totalveintiochoo','image'=>'imgo (28).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12344','NombreProducto' => 'productoveintinueveo','NombreVariable' =>  'veintinueveo','NombrePrecio' =>'precioveintinueveo','NombreTotalPrecio' =>'totalprecioveintinueveo','DescripcionProducto' => 'GUM CEP CLASSIC 411 SUAVE','Precio'=> '240','NombrePirce'=>'pirceveintinueveo','NombreDiv'=>'totalveintinueveo','image'=>'imgo (29).jpg']);
DB::table('bucales')->insert(['Codigo' =>'12345','NombreProducto' => 'productotreintao','NombreVariable' =>  'treintao','NombrePrecio' =>'preciotreintao','NombreTotalPrecio' =>'totalpreciotreintao','DescripcionProducto' => 'GUM CEP ORTODONTICO 124 SUAVE','Precio'=> '240','NombrePirce'=>'pircetreintao','NombreDiv'=>'totaltreintao','image'=>'imgo (30).jpg']);
    }
}
