<?php

use Illuminate\Database\Seeder;

class CapilaresSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {   DB::table('capilares')->truncate();
        DB::table('capilares')->insert(['Codigo' =>'12344','NombreProducto' => 'productounoca','NombreVariable' =>'unoca','NombrePrecio' =>'preciounoca','NombreTotalPrecio' =>'totalpreciounoca','DescripcionProducto' => 'ELVIVE SH CITRUS X 200','Precio'=> '195 ','NombrePirce'=>'pirceunoca','NombreDiv'=>'totalunoca','image'=>'imgca (1).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12345','NombreProducto' => 'productodosca','NombreVariable' =>'dosca','NombrePrecio' =>'preciodosca','NombreTotalPrecio' =>'totalpreciodosca','DescripcionProducto' => ' ELVIVE SH COLOR-VIVE X 200','Precio'=> '195 ','NombrePirce'=>'pircedosca','NombreDiv'=>'totaldosca','image'=>'imgca (2).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12344','NombreProducto' => 'productotresca','NombreVariable' =>'tresca','NombrePrecio' =>'preciotresca','NombreTotalPrecio' =>'totalpreciotresca','DescripcionProducto' =>  ' ELVIVE SH DREAM LONG LISS X 200','Precio'=> '195','NombrePirce'=>'pircetresca','NombreDiv'=>'totaltresca','image'=>'imgca (3).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12345','NombreProducto' => 'productocuatroca','NombreVariable' =>'cuatroca','NombrePrecio' =>'preciocuatroca','NombreTotalPrecio' =>'totalpreciocuatroca','DescripcionProducto' => ' ELVIVE SH FIBRALOGY X 200','Precio'=> '195','NombrePirce'=>'pircecuatroca','NombreDiv'=>'totalcuatroca','image'=>'imgca (4).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12344','NombreProducto' => 'productocincoca','NombreVariable' =>'cincoca','NombrePrecio' =>'preciocincoca','NombreTotalPrecio' =>'totalpreciocincoca','DescripcionProducto' => 'ELVIVE SH LOW REPARACION TOTAL 5 X 400','Precio'=> '430','NombrePirce'=>'pircecincoca','NombreDiv'=>'totalcincoca','image'=>'imgca (5).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12345','NombreProducto' => 'productoseisca','NombreVariable' =>'seisca','NombrePrecio' =>'precioseisca','NombreTotalPrecio' =>'totalprecioseisca','DescripcionProducto' => 'ELVIVE SH OIL SUMMER EDIT X 200','Precio'=> '195','NombrePirce'=>'pirceseisca','NombreDiv'=>'totalseisca','image'=>'imgca (6).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12344','NombreProducto' => 'productosieteca','NombreVariable' =>'sieteca','NombrePrecio' =>'preciosieteca','NombreTotalPrecio' =>'totalpreciosieteca','DescripcionProducto' =>'ELVIVE AC COLOR-VIVE X 200','Precio'=> '195','NombrePirce'=>'pircesieteca','NombreDiv'=>'totalsieteca','image'=>'imgca (7).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12345','NombreProducto' => 'productoochoca','NombreVariable' =>'ochoca','NombrePrecio' =>'precioochoca','NombreTotalPrecio' =>'totalprecioochoca','DescripcionProducto' => ' ELVIVE AC DREAM LENGTH X 200','Precio'=> '195 ','NombrePirce'=>'pirceochoca','NombreDiv'=>'totalochoca','image'=>'imgca (8).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12344','NombreProducto' => 'productonueveca','NombreVariable' =>'nueveca','NombrePrecio' =>'precionueveca','NombreTotalPrecio' =>'totalprecionueveca','DescripcionProducto' => ' ELVIVE AC DREAM LONG LISS X 200','Precio'=> '195','NombrePirce'=>'pircenueveca','NombreDiv'=>'totalnueveca','image'=>'imgca (9).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12345','NombreProducto' => 'productodiezca','NombreVariable' =>'diezca','NombrePrecio' =>'preciodiezca','NombreTotalPrecio' =>'totalpreciodiezca','DescripcionProducto' => ' ELVIVE TRAT OLEO EXTR ACEITE X 100 ML','Precio'=> '550','NombrePirce'=>'pircediezca','NombreDiv'=>'totaldiezca','image'=>'imgca (10).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12344','NombreProducto' => 'productoonceca','NombreVariable' =>'onceca','NombrePrecio' =>'precioonceca','NombreTotalPrecio' =>'totalprecioonceca','DescripcionProducto' => ' PANTENE 2EN1 CUID CLASICO X 200','Precio'=> '195','NombrePirce'=>'pirceonceca','NombreDiv'=>'totalonceca','image'=>'imgca (11).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12345','NombreProducto' => 'productodoceca','NombreVariable' =>'doceca','NombrePrecio' =>'preciodoceca','NombreTotalPrecio' =>'totalpreciodoceca','DescripcionProducto' => ' PANTENE AC 3MM LISO EXTREMO X 170','Precio'=> '285','NombrePirce'=>'pircedoceca','NombreDiv'=>'totaldoceca','image'=>'imgca (12).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12344','NombreProducto' => 'productotrececa','NombreVariable' =>'trececa','NombrePrecio' =>'preciotrececa','NombreTotalPrecio' =>'totalpreciotrececa','DescripcionProducto' => ' PANTENE AC 3MM RIZOS DEFINIDOS X 170','Precio'=> '285','NombrePirce'=>'pircetrececa','NombreDiv'=>'totaltrececa','image'=>'imgca (13).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12345','NombreProducto' => 'productocatorceca','NombreVariable' =>'catorceca','NombrePrecio' =>'preciocatorceca','NombreTotalPrecio' =>'totalpreciocatorceca','DescripcionProducto' => ' PANTENE AC BRILLO EXTREMO X 200','Precio'=> '195','NombrePirce'=>'pircecatorceca','NombreDiv'=>'totalcatorceca','image'=>'imgca (14).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12344','NombreProducto' => 'productoquinceca','NombreVariable' =>'quinceca','NombrePrecio' =>'precioquinceca','NombreTotalPrecio' =>'totalprecioquinceca','DescripcionProducto' => ' PANTENE AC CONTROL CAIDA X 200','Precio'=> '195 ','NombrePirce'=>'pircequinceca','NombreDiv'=>'totalquinceca','image'=>'imgca (15).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12345','NombreProducto' => 'productodieciseisca','NombreVariable' =>'dieciseisca','NombrePrecio' =>'preciodieciseisca','NombreTotalPrecio' =>'totalpreciodieciseisca','DescripcionProducto' =>'PANTENE SH LISO EXTREMO X 200','Precio'=> '195 ','NombrePirce'=>'pircedieciseisca','NombreDiv'=>'totaldieciseisca','image'=>'imgca (16).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12344','NombreProducto' => 'productodiecisieteca','NombreVariable' =>'diecisieteca','NombrePrecio' =>'preciodiecisieteca','NombreTotalPrecio' =>'totalpreciodiecisieteca','DescripcionProducto' =>'PANTENE SH MICELLAR X 200','Precio'=> '195 ','NombrePirce'=>'pircediecisieteca','NombreDiv'=>'totaldiecisieteca','image'=>'imgca (17).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12345','NombreProducto' => 'productodieciochoca','NombreVariable' =>'dieciochoca','NombrePrecio' =>'preciodieciochoca','NombreTotalPrecio' =>'totalpreciodieciochoca','DescripcionProducto' => 'PANTENE SH RESTAURACION X 200','Precio'=> '195 ','NombrePirce'=>'pircedieciochoca','NombreDiv'=>'totaldieciochoca','image'=>'imgca (18).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12344','NombreProducto' => 'productodiecinueveca','NombreVariable' =>'diecinueveca','NombrePrecio' =>'preciodiecinueveca','NombreTotalPrecio' =>'totalpreciodiecinueveca','DescripcionProducto' =>'PANTENE TRAT SPRAY MICELLAR X 160','Precio'=> '295','NombrePirce'=>'pircediecinueveca','NombreDiv'=>'totaldiecinueveca','image'=>'imgca (19).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12345','NombreProducto' => 'productoveinteca','NombreVariable' =>'veinteca','NombrePrecio' =>'precioveinteca','NombreTotalPrecio' =>'totalprecioveinteca','DescripcionProducto' => 'PANTENE SH MIRACLE RIZOS DEF X 270','Precio'=> '295 ','NombrePirce'=>'pirceveinteca','NombreDiv'=>'totalveinteca','image'=>'imgca (20).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12344','NombreProducto' => 'productoveintiunoca','NombreVariable' =>'veintiunoca','NombrePrecio' =>'precioveintiunoca','NombreTotalPrecio' =>'totalprecioveintiunoca','DescripcionProducto' => ' SEDAL SH BOMBA COCO X 650.','Precio'=> '290 ','NombrePirce'=>'pirceveintiunoca','NombreDiv'=>'totalveintiunoca','image'=>'imgca (21).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12345','NombreProducto' => 'productoveintidosca','NombreVariable' =>'veintidosca','NombrePrecio' =>'precioveintidosca','NombreTotalPrecio' =>'totalprecioveintidosca','DescripcionProducto' => ' SEDAL MASC CAPILAR NUTRE X 300ML','Precio'=> '230','NombrePirce'=>'pirceveintidosca','NombreDiv'=>'totalveintidosca','image'=>'imgca (22).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12344','NombreProducto' => 'productoveintitresca','NombreVariable' =>'veintitresca','NombrePrecio' =>'precioveintitresca','NombreTotalPrecio' =>'totalprecioveintitresca','DescripcionProducto' => ' SEDAL SH BOM NUTRICION X 190','Precio'=> '130 ','NombrePirce'=>'pirceveintitresca','NombreDiv'=>'totalveintitresca','image'=>'imgca (23).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12345','NombreProducto' => 'productoveinticuatroca','NombreVariable' =>'veinticuatroca','NombrePrecio' =>'precioveinticuatroca','NombreTotalPrecio' =>'totalprecioveinticuatroca','DescripcionProducto' => ' SEDAL SH BOMBA ARGAN X190 ML','Precio'=> '130','NombrePirce'=>'pirceveinticuatroca','NombreDiv'=>'totalveinticuatroca','image'=>'imgca (24).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12344','NombreProducto' => 'productoveinticincoca','NombreVariable' =>'veinticincoca','NombrePrecio' =>'precioveinticincoca','NombreTotalPrecio' =>'totalprecioveinticincoca','DescripcionProducto' => ' SEDAL SH CERAMIDAS X 340','Precio'=> '195 ','NombrePirce'=>'pirceveinticincoca','NombreDiv'=>'totalveinticincoca','image'=>'imgca (25).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12345','NombreProducto' => 'productoveintiseisca','NombreVariable' =>'veintiseisca','NombrePrecio' =>'precioveintiseisca','NombreTotalPrecio' =>'totalprecioveintiseisca','DescripcionProducto' => ' SEDAL AC BALANCE RTO X 300','Precio'=> '145','NombrePirce'=>'pirceveintiseisca','NombreDiv'=>'totalveintiseisca','image'=>'imgca (26).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12344','NombreProducto' => 'productoveintisieteca','NombreVariable' =>'veintisieteca','NombrePrecio' =>'precioveintisieteca','NombreTotalPrecio' =>'totalprecioveintisieteca','DescripcionProducto' => 'SEDAL AC BOMBA ARGAN X 340','Precio'=> '195 ','NombrePirce'=>'pirceveintisieteca','NombreDiv'=>'totalveintisieteca','image'=>'imgca (27).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12345','NombreProducto' => 'productoveintiochoca','NombreVariable' =>'veintiochoca','NombrePrecio' =>'precioveintiochoca','NombreTotalPrecio' =>'totalprecioveintiochoca','DescripcionProducto' => 'SEDAL AC BOMBA COCO X 190','Precio'=> '130','NombrePirce'=>'pirceveintiochoca','NombreDiv'=>'totalveintiochoca','image'=>'imgca (28).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12344','NombreProducto' => 'productoveintinueveca','NombreVariable' =>'veintinueveca','NombrePrecio' =>'precioveintinueveca','NombreTotalPrecio' =>'totalprecioveintinueveca','DescripcionProducto' =>'SEDAL AC CERAMIDAS X 190','Precio'=> '130 ','NombrePirce'=>'pirceveintinueveca','NombreDiv'=>'totalveintinueveca','image'=>'imgca (29).jpg']);
DB::table('capilares')->insert(['Codigo' =>'12345','NombreProducto' => 'productotreintaca','NombreVariable' =>'treintaca','NombrePrecio' =>'preciotreintaca','NombreTotalPrecio' =>'totalpreciotreintaca','DescripcionProducto' => 'SEDAL AC CREMA BALANCE X 340','Precio'=> '195 ','NombrePirce'=>'pircetreintaca','NombreDiv'=>'totaltreintaca','image'=>'imgca (30).jpg']);

    }
}
