<?php

use Illuminate\Database\Seeder;

class CorporalesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {   DB::table('corporales')->truncate();
       DB::table('corporales')->insert(['Codigo' =>'12344','NombreProducto' => 'productounoco','NombreVariable' =>  'unoco','NombrePrecio' =>'preciounoco','NombreTotalPrecio' =>'totalpreciounoco','DescripcionProducto' => 'NEUTROGENA BODY CARE INTENSIVE EXTRA CARE X 400 ','Precio'=> '440 ','NombrePirce'=>'pirceunoco','NombreDiv'=>'totalunoco','image'=>'imgco (1).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12345','NombreProducto' => 'productodosco','NombreVariable' =>  'dosco','NombrePrecio' =>'preciodosco','NombreTotalPrecio' =>'totalpreciodosco','DescripcionProducto' => ' CICATRICURE 25 % OFF ANTI EDAD X 400ML','Precio'=> '290','NombrePirce'=>'pircedosco','NombreDiv'=>'totaldosco','image'=>'imgco (2).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12344','NombreProducto' => 'productotresco','NombreVariable' =>  'tresco','NombrePrecio' =>'preciotresco','NombreTotalPrecio' =>'totalpreciotresco','DescripcionProducto' => ' CICATRICURE 25% OFF CR ANTI-ESTRIAS X 400ML','Precio'=> '290','NombrePirce'=>'pircetresco','NombreDiv'=>'totaltresco','image'=>'imgco (3).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12345','NombreProducto' => 'productocuatroco','NombreVariable' =>  'cuatroco','NombrePrecio' =>'preciocuatroco','NombreTotalPrecio' =>'totalpreciocuatroco','DescripcionProducto' => 'GOICOECHEA CR CELLUMODEL NF X 400','Precio'=> '490','NombrePirce'=>'pircecuatroco','NombreDiv'=>'totalcuatroco','image'=>'imgco (4).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12344','NombreProducto' => 'productocincoco','NombreVariable' =>  'cincoco','NombrePrecio' =>'preciocincoco','NombreTotalPrecio' =>'totalpreciocincoco','DescripcionProducto' => ' GOICOECHEA CR COVER NF X 95 GR','Precio'=> '490','NombrePirce'=>'pircecincoco','NombreDiv'=>'totalcincoco','image'=>'imgco (5).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12345','NombreProducto' => 'productoseisco','NombreVariable' =>  'seisco','NombrePrecio' =>'precioseisco','NombreTotalPrecio' =>'totalprecioseisco','DescripcionProducto' => 'GOICOECHEA CR INV. ALMENDRA X400','Precio'=> '390','NombrePirce'=>'pirceseisco','NombreDiv'=>'totalseisco','image'=>'imgco (6).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12344','NombreProducto' => 'productosieteco','NombreVariable' =>  'sieteco','NombrePrecio' =>'preciosieteco','NombreTotalPrecio' =>'totalpreciosieteco','DescripcionProducto' => 'GOICOECHEA CR ULTRA NUTRITIVA X 200','Precio'=> '230','NombrePirce'=>'pircesieteco','NombreDiv'=>'totalsieteco','image'=>'imgco (7).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12345','NombreProducto' => 'productoochoco','NombreVariable' =>  'ochoco','NombrePrecio' =>'precioochoco','NombreTotalPrecio' =>'totalprecioochoco','DescripcionProducto' => ' GOICOECHEA CR ULTRA NUTRITIVA X 200','Precio'=> '390 ','NombrePirce'=>'pirceochoco','NombreDiv'=>'totalochoco','image'=>'imgco (8).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12344','NombreProducto' => 'productonueveco','NombreVariable' =>  'nueveco','NombrePrecio' =>'precionueveco','NombreTotalPrecio' =>'totalprecionueveco','DescripcionProducto' => 'GOICOECHEA DETOX X 400 ML','Precio'=> '460 ','NombrePirce'=>'pircenueveco','NombreDiv'=>'totalnueveco','image'=>'imgco (9).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12345','NombreProducto' => 'productodiezco','NombreVariable' =>  'diezco','NombrePrecio' =>'preciodiezco','NombreTotalPrecio' =>'totalpreciodiezco','DescripcionProducto' => 'GOICOECHEA DIABET TX CALENDULA X 200 ML','Precio'=> '390 ','NombrePirce'=>'pircediezco','NombreDiv'=>'totaldiezco','image'=>'imgco (10).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12344','NombreProducto' => 'productoonceco','NombreVariable' =>  'onceco','NombrePrecio' =>'precioonceco','NombreTotalPrecio' =>'totalprecioonceco','DescripcionProducto' => 'GOICOECHEA DIABETX TALCO LIQUIDO X70ML','Precio'=> '390 ','NombrePirce'=>'pirceonceco','NombreDiv'=>'totalonceco','image'=>'imgco (11).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12345','NombreProducto' => 'productodoceco','NombreVariable' =>  'doceco','NombrePrecio' =>'preciodoceco','NombreTotalPrecio' =>'totalpreciodoceco','DescripcionProducto' => 'GOICOECHEA MASCARA ANTI-CELULITIS X200','Precio'=> '750','NombrePirce'=>'pircedoceco','NombreDiv'=>'totaldoceco','image'=>'imgco (12).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12344','NombreProducto' => 'productotrececo','NombreVariable' =>  'trececo','NombrePrecio' =>'preciotrececo','NombreTotalPrecio' =>'totalpreciotrececo','DescripcionProducto' => ' DERMAGLOS CORP EMUL X 300 GRS','Precio'=> '790','NombrePirce'=>'pircetrececo','NombreDiv'=>'totaltrececo','image'=>'imgco (13).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12345','NombreProducto' => 'productocatorceco','NombreVariable' =>  'catorceco','NombrePrecio' =>'preciocatorceco','NombreTotalPrecio' =>'totalpreciocatorceco','DescripcionProducto' => ' DERMAGLOS CORP HID PROFUNDA CR X 200 GR','Precio'=> '750 ','NombrePirce'=>'pircecatorceco','NombreDiv'=>'totalcatorceco','image'=>'imgco (14).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12344','NombreProducto' => 'productoquinceco','NombreVariable' =>  'quinceco','NombrePrecio' =>'precioquinceco','NombreTotalPrecio' =>'totalprecioquinceco','DescripcionProducto' => 'DERMAGLOS CREMA X 50 GRS','Precio'=> '350','NombrePirce'=>'pircequinceco','NombreDiv'=>'totalquinceco','image'=>'imgco (15).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12345','NombreProducto' => 'productodieciseisco','NombreVariable' =>  'dieciseisco','NombrePrecio' =>'preciodieciseisco','NombreTotalPrecio' =>'totalpreciodieciseisco','DescripcionProducto' => 'DERMAGLOS EMUL X 400 ML','Precio'=> '1310 ','NombrePirce'=>'pircedieciseisco','NombreDiv'=>'totaldieciseisco','image'=>'imgco (16).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12344','NombreProducto' => 'productodiecisieteco','NombreVariable' =>  'diecisieteco','NombrePrecio' =>'preciodiecisieteco','NombreTotalPrecio' =>'totalpreciodiecisieteco','DescripcionProducto' => 'BAGOVIT A AUTOBRONC EMUL X 200 GRS','Precio'=> '850','NombrePirce'=>'pircediecisieteco','NombreDiv'=>'totaldiecisieteco','image'=>'imgco (17).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12345','NombreProducto' => 'productodieciochoco','NombreVariable' =>  'dieciochoco','NombrePrecio' =>'preciodieciochoco','NombreTotalPrecio' =>'totalpreciodieciochoco','DescripcionProducto' => 'BAGOVIT A LIGHT CREMA X 100 GRS','Precio'=> '550 ','NombrePirce'=>'pircedieciochoco','NombreDiv'=>'totaldieciochoco','image'=>'imgco (18).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12344','NombreProducto' => 'productodiecinueveco','NombreVariable' =>  'diecinueveco','NombrePrecio' =>'preciodiecinueveco','NombreTotalPrecio' =>'totalpreciodiecinueveco','DescripcionProducto' => 'BAGOVIT A EMUL X 200 GRS','Precio'=> '600 ','NombrePirce'=>'pircediecinueveco','NombreDiv'=>'totaldiecinueveco','image'=>'imgco (19).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12345','NombreProducto' => 'productoveinteco','NombreVariable' =>  'veinteco','NombrePrecio' =>'precioveinteco','NombreTotalPrecio' =>'totalprecioveinteco','DescripcionProducto' => 'ST.IVES CR CORP EXOTIC NATURALS X532','Precio'=> '280','NombrePirce'=>'pirceveinteco','NombreDiv'=>'totalveinteco','image'=>'imgco (20).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12344','NombreProducto' => 'productoveintiunoco','NombreVariable' =>  'veintiunoco','NombrePrecio' =>'precioveintiunoco','NombreTotalPrecio' =>'totalprecioveintiunoco','DescripcionProducto' => 'ST.IVES CR CORP HUMECT INTENS X 532','Precio'=> '320 ','NombrePirce'=>'pirceveintiunoco','NombreDiv'=>'totalveintiunoco','image'=>'imgco (21).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12345','NombreProducto' => 'productoveintidosco','NombreVariable' =>  'veintidosco','NombrePrecio' =>'precioveintidosco','NombreTotalPrecio' =>'totalprecioveintidosco','DescripcionProducto' => 'ST.IVES CR CORP PIEL RENOVADA X 532','Precio'=> '280 ','NombrePirce'=>'pirceveintidosco','NombreDiv'=>'totalveintidosco','image'=>'imgco (22).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12344','NombreProducto' => 'productoveintitresco','NombreVariable' =>  'veintitresco','NombrePrecio' =>'precioveintitresco','NombreTotalPrecio' =>'totalprecioveintitresco','DescripcionProducto' => ' HINDS ANTI-AGE PLUS EMUL X 250','Precio'=> '250','NombrePirce'=>'pirceveintitresco','NombreDiv'=>'totalveintitresco','image'=>'imgco (23).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12345','NombreProducto' => 'productoveinticuatroco','NombreVariable' =>  'veinticuatroco','NombrePrecio' =>'precioveinticuatroco','NombreTotalPrecio' =>'totalprecioveinticuatroco','DescripcionProducto' => 'HINDS HIDRATACION ESENCIAL X 250','Precio'=> '210 ','NombrePirce'=>'pirceveinticuatroco','NombreDiv'=>'totalveinticuatroco','image'=>'imgco (24).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12344','NombreProducto' => 'productoveinticincoco','NombreVariable' =>  'veinticincoco','NombrePrecio' =>'precioveinticincoco','NombreTotalPrecio' =>'totalprecioveinticincoco','DescripcionProducto' => ' HINDS REAFIRMANTE X 250','Precio'=> '210 ','NombrePirce'=>'pirceveinticincoco','NombreDiv'=>'totalveinticincoco','image'=>'imgco (25).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12345','NombreProducto' => 'productoveintiseisco','NombreVariable' =>  'veintiseisco','NombrePrecio' =>'precioveintiseisco','NombreTotalPrecio' =>'totalprecioveintiseisco','DescripcionProducto' => 'HINDS HIDRATACION ESENCIAL X 250','Precio'=> '370','NombrePirce'=>'pirceveintiseisco','NombreDiv'=>'totalveintiseisco','image'=>'imgco (26).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12344','NombreProducto' => 'productoveintisieteco','NombreVariable' =>  'veintisieteco','NombrePrecio' =>'precioveintisieteco','NombreTotalPrecio' =>'totalprecioveintisieteco','DescripcionProducto' => 'NIVEA CREME LATA X 60','Precio'=> '170','NombrePirce'=>'pirceveintisieteco','NombreDiv'=>'totalveintisieteco','image'=>'imgco (27).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12345','NombreProducto' => 'productoveintiochoco','NombreVariable' =>  'veintiochoco','NombrePrecio' =>'precioveintiochoco','NombreTotalPrecio' =>'totalprecioveintiochoco','DescripcionProducto' =>
'NIVEA CREME POTE X 100','Precio'=> '270 ','NombrePirce'=>'pirceveintiochoco','NombreDiv'=>'totalveintiochoco','image'=>'imgco (28).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12344','NombreProducto' => 'productoveintinueveco','NombreVariable' =>  'veintinueveco','NombrePrecio' =>'precioveintinueveco','NombreTotalPrecio' =>'totalprecioveintinueveco','DescripcionProducto' => 'NIVEA BODY PIERNAS RELAJ ANTICELULITIS X 400','Precio'=> '390','NombrePirce'=>'pirceveintinueveco','NombreDiv'=>'totalveintinueveco','image'=>'imgco (29).jpg']);
DB::table('corporales')->insert(['Codigo' =>'12345','NombreProducto' => 'productotreintaco','NombreVariable' =>  'treintaco','NombrePrecio' =>'preciotreintaco','NombreTotalPrecio' =>'totalpreciotreintaco','DescripcionProducto' => 'NIVEA BODY P/NORMAL X 125 (BODY LOTION)','Precio'=> '250','NombrePirce'=>'pircetreintaco','NombreDiv'=>'totaltreintaco','image'=>'imgco (30).jpg']);

    }
}
