<?php

use Illuminate\Database\Seeder;

class MujeresSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
     DB::table('mujeres')->truncate();
DB::table('mujeres')->insert(['Codigo' =>'123445','NombreProducto' => 'productounom','NombreVariable' =>  'unom','NombrePrecio' =>  'preciounom','NombreTotalPrecio' =>'totalpreciounom','DescripcionProducto' => ' Tintura EXCELLENCE LORELA. Consultar Colores! ','Precio'=>  '590 ','NombrePirce'=>'pirceunom','NombreDiv'=>'totalunom','image'=>'imgm (1).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12345','NombreProducto' => 'productodosm','NombreVariable' =>  'dosm','NombrePrecio' =>  'preciodosm','NombreTotalPrecio' =>'totalpreciodosm','DescripcionProducto' => 'Kit Tintura FARMACOLOR. Consultar Colores!','Precio'=>  '330 ','NombrePirce'=>'pircedosm','NombreDiv'=>'totaldosm','image'=>'imgm (2).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12344','NombreProducto' => 'productotresm','NombreVariable' =>  'tresm','NombrePrecio' =>  'preciotresm','NombreTotalPrecio' =>'totalpreciotresm','DescripcionProducto' => 'Tintura FARMACOLOR Individual. Consultar Colores!','Precio'=>  '180 ','NombrePirce'=>'pircetresm','NombreDiv'=>'totaltresm','image'=>'imgm (3).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12345','NombreProducto' => 'productocuatrom','NombreVariable' =>  'cuatrom','NombrePrecio' =>  'preciocuatrom','NombreTotalPrecio' =>'totalpreciocuatrom','DescripcionProducto' => ' Agua Oxigenada Crema 20 Vol.','Precio'=>  '100 ','NombrePirce'=>'pircecuatrom','NombreDiv'=>'totalcuatrom','image'=>'imgm (4).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12344','NombreProducto' => 'productocincom','NombreVariable' =>  'cincom','NombrePrecio' =>  'preciocincom','NombreTotalPrecio' =>'totalpreciocincom','DescripcionProducto' => ' Tintura ALFAPARFKit. Consultar Colores!','Precio'=>  '390 ','NombrePirce'=>'pircecincom','NombreDiv'=>'totalcincom','image'=>'imgm (5).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12345','NombreProducto' => 'productoseism','NombreVariable' =>  'seism','NombrePrecio' =>  'precioseism','NombreTotalPrecio' =>'totalprecioseism','DescripcionProducto' => 'ALFAPARF Color Protección','Precio'=>  '190 ','NombrePirce'=>'pirceseism','NombreDiv'=>'totalseism','image'=>'imgm (6).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12344','NombreProducto' => 'productosietem','NombreVariable' =>  'sietem','NombrePrecio' =>  'preciosietem','NombreTotalPrecio' =>'totalpreciosietem','DescripcionProducto' => ' ALFAPARF Ampolla Repair y Defense x 3','Precio'=>  '350 ','NombrePirce'=>'pircesietem','NombreDiv'=>'totalsietem','image'=>'imgm (7).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12345','NombreProducto' => 'productoochom','NombreVariable' =>  'ochom','NombrePrecio' =>  'precioochom','NombreTotalPrecio' =>'totalprecioochom','DescripcionProducto' => ' CUTEX Esmaltes. Consultar Colores!','Precio'=>  '140 ','NombrePirce'=>'pirceochom','NombreDiv'=>'totalochom','image'=>'imgm (8).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12344','NombreProducto' => 'productonuevem','NombreVariable' =>  'nuevem','NombrePrecio' =>  'precionuevem','NombreTotalPrecio' =>'totalprecionuevem','DescripcionProducto' => 'IDI Esmaltes. Consultar Colores!','Precio'=> '140 ','NombrePirce'=>'pircenuevem','NombreDiv'=>'totalnuevem','image'=>'imgm (9).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12345','NombreProducto' => 'productodiezm','NombreVariable' =>  'diezm','NombrePrecio' =>  'preciodiezm','NombreTotalPrecio' =>'totalpreciodiezm','DescripcionProducto' => 'MYBELLINI Base Líquida.Consultar tonos!','Precio'=> '950 ','NombrePirce'=>'pircediezm','NombreDiv'=>'totaldiezm','image'=>'imgm (10).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12344','NombreProducto' => 'productooncem','NombreVariable' =>  'oncem','NombrePrecio' =>  'preciooncem','NombreTotalPrecio' =>'totalpreciooncem','DescripcionProducto' => ' MYBELLINI Base Líquida + Poreless.Consultar tonos!','Precio'=> '590 ','NombrePirce'=>'pirceoncem','NombreDiv'=>'totaloncem','image'=>'imgm (11).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12345','NombreProducto' => 'productodocem','NombreVariable' =>  'docem','NombrePrecio' =>  'preciodocem','NombreTotalPrecio' =>'totalpreciodocem','DescripcionProducto' => ' Esmaltes EVE MALCRIATE. Consultar Colores!','Precio'=> '140 ','NombrePirce'=>'pircedocem','NombreDiv'=>'totaldocem','image'=>'imgm (12).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12344','NombreProducto' => 'productotrecem','NombreVariable' =>  'trecem','NombrePrecio' =>  'preciotrecem','NombreTotalPrecio' =>'totalpreciotrecem','DescripcionProducto' => 'EV Aceite para uñas','Precio'=> '350 ','NombrePirce'=>'pircetrecem','NombreDiv'=>'totaltrecem','image'=>'imgm (13).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12345','NombreProducto' => 'productocatorcem','NombreVariable' =>  'catorcem','NombrePrecio' =>  'preciocatorcem','NombreTotalPrecio' =>'totalpreciocatorcem','DescripcionProducto' => 'EV Aceite para uñas Post UV','Precio'=> '250 ','NombrePirce'=>'pircecatorcem','NombreDiv'=>'totalcatorcem','image'=>'imgm (14).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12344','NombreProducto' => 'productoquincem','NombreVariable' =>  'quincem','NombrePrecio' =>  'precioquincem','NombreTotalPrecio' =>'totalprecioquincem','DescripcionProducto' => 'REVLON Tintura. Consultar Colores!','Precio'=> '250 ','NombrePirce'=>'pircequincem','NombreDiv'=>'totalquincem','image'=>'imgm (15).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12345','NombreProducto' => 'productodieciseism','NombreVariable' =>  'dieciseism','NombrePrecio' =>  'preciodieciseism','NombreTotalPrecio' =>'totalpreciodieciseism','DescripcionProducto' => ' REVLON Delin Colorstay Líquido Negro','Precio'=> '730 ','NombrePirce'=>'pircedieciseism','NombreDiv'=>'totaldieciseism','image'=>'imgm (16).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12344','NombreProducto' => 'productodiecisietem','NombreVariable' =>  'diecisietem','NombrePrecio' =>  'preciodiecisietem','NombreTotalPrecio' =>'totalpreciodiecisietem','DescripcionProducto' => ' MAYBELLINE Polvo Compacto. Consultar Tonos!','Precio'=> '460 ','NombrePirce'=>'pircediecisietem','NombreDiv'=>'totaldiecisietem','image'=>'imgm (17).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12345','NombreProducto' => 'productodieciochom','NombreVariable' =>  'dieciochom','NombrePrecio' =>  'preciodieciochom','NombreTotalPrecio' =>'totalpreciodieciochom','DescripcionProducto' => ' MAYBELLINE Delin Ojos Negro','Precio'=> '710 ','NombrePirce'=>'pircedieciochom','NombreDiv'=>'totaldieciochom','image'=>'imgm (18).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12344','NombreProducto' => 'productodiecinuevem','NombreVariable' =>  'diecinuevem','NombrePrecio' =>  'preciodiecinuevem','NombreTotalPrecio' =>'totalpreciodiecinuevem','DescripcionProducto' => ' ISSUE Tintura Kit. Consultar Colores!','Precio'=> '230 ','NombrePirce'=>'pircediecinuevem','NombreDiv'=>'totaldiecinuevem','image'=>'imgm (19).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12345','NombreProducto' => 'productoveintem','NombreVariable' =>  'veintem','NombrePrecio' =>  'precioveintem','NombreTotalPrecio' =>'totalprecioveintem','DescripcionProducto' => ' ISSUE Tintura Individual. Consultar Colores!','Precio'=>'160 ','NombrePirce'=>'pirceveintem','NombreDiv'=>'totalveintem','image'=>'imgm (20).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12344','NombreProducto' => 'productoveintiunom','NombreVariable' =>  'veintiunom','NombrePrecio' =>  'precioveintiunom','NombreTotalPrecio' =>'totalprecioveintiunom','DescripcionProducto' => 'REVLON Esmalte. Consultar Color!','Precio'=> '400 ','NombrePirce'=>'pirceveintiunom','NombreDiv'=>'totalveintiunom','image'=>'imgm (21).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12345','NombreProducto' => 'productoveintidosm','NombreVariable' =>  'veintidosm','NombrePrecio' =>  'precioveintidosm','NombreTotalPrecio' =>'totalprecioveintidosm','DescripcionProducto' => 'EUCERIN Volum Filler día. CONSULTAR TODA LINEA!!','Precio'=> '3100 ','NombrePirce'=>'pirceveintidosm','NombreDiv'=>'totalveintidosm','image'=>'imgm (22).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12344','NombreProducto' => 'productoveintitresm','NombreVariable' =>  'veintitresm','NombrePrecio' =>  'precioveintitresm','NombreTotalPrecio' =>'totalprecioveintitresm','DescripcionProducto' => 'CUTEX Quitaesmalte, 100ml. Consultar Variedad!','Precio'=> '90 ','NombrePirce'=>'pirceveintitresm','NombreDiv'=>'totalveintitresm','image'=>'imgm (23).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12345','NombreProducto' => 'productoveinticuatrom','NombreVariable' =>  'veinticuatrom','NombrePrecio' =>  'precioveinticuatrom','NombreTotalPrecio' =>'totalprecioveinticuatrom','DescripcionProducto' => 'ESTRELLA Discos, 80 Unidades','Precio'=> '110','NombrePirce'=>'pirceveinticuatrom','NombreDiv'=>'totalveinticuatrom','image'=>'imgm (24).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12344','NombreProducto' => 'productoveinticincom','NombreVariable' =>  'veinticincom','NombrePrecio' =>  'precioveinticincom','NombreTotalPrecio' =>'totalprecioveinticincom','DescripcionProducto' => 'CICATRICURE Cicatrices y Arrugas.','Precio'=> '760 ','NombrePirce'=>'pirceveinticincom','NombreDiv'=>'totalveinticincom','image'=>'imgm (25).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12345','NombreProducto' => 'productoveintiseism','NombreVariable' =>  'veintiseism','NombrePrecio' =>  'precioveintiseism','NombreTotalPrecio' =>'totalprecioveintiseism','DescripcionProducto' => 'CICATRICURE Contorno Dúo','Precio'=> '950 ','NombrePirce'=>'pirceveintiseism','NombreDiv'=>'totalveintiseism','image'=>'imgm (26).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12344','NombreProducto' => 'productoveintisietem','NombreVariable' =>  'veintisietem','NombrePrecio' =>  'precioveintisietem','NombreTotalPrecio' =>'totalprecioveintisietem','DescripcionProducto' => 'CICATRICURE AGUA MICELAR','Precio'=> '420 ','NombrePirce'=>'pirceveintisietem','NombreDiv'=>'totalveintisietem','image'=>'imgm (27).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12345','NombreProducto' => 'productoveintiochom','NombreVariable' =>  'veintiochom','NombrePrecio' =>  'precioveintiochom','NombreTotalPrecio' =>'totalprecioveintiochom','DescripcionProducto' => 'DERMAGLOS Demaquillante Bifaz de ojos','Precio'=> '590 ','NombrePirce'=>'pirceveintiochom','NombreDiv'=>'totalveintiochom','image'=>'imgm (28).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12344','NombreProducto' => 'productoveintinuevem','NombreVariable' =>  'veintinuevem','NombrePrecio' =>  'precioveintinuevem','NombreTotalPrecio' =>'totalprecioveintinuevem','DescripcionProducto' => 'NIVEA Toallas Demaq.x25.','Precio'=> '290 ','NombrePirce'=>'pirceveintinuevem','NombreDiv'=>'totalveintinuevem','image'=>'imgm (29).jpg']);
DB::table('mujeres')->insert(['Codigo' =>'12345','NombreProducto' => 'productotreintam','NombreVariable' =>  'treintam','NombrePrecio' =>  'preciotreintam','NombreTotalPrecio' =>'totalpreciotreintam','DescripcionProducto' => 'CICATRICURE Corporal. Consultar Variedad!','Precio'=> '365 ','NombrePirce'=>'pircetreintam','NombreDiv'=>'totaltreintam','image'=>'imgm (30).jpg']);

}
}